language: node_js
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directories:
    - "node_modules"
  yarn: true
sudo: false
after_success:
  - npm run test